"""Aggregate router mounting every v1 endpoint group."""

from __future__ import annotations

from fastapi import APIRouter

from app.api.v1 import (
    absences,
    account,
    appointments,
    auth,
    automations,
    automations_run,
    biology,
    capture,
    catalog,
    clinical,
    conditions,
    dashboard,
    data,
    events,
    evidence,
    evolution,
    export,
    health_records,
    imports,
    ingest,
    journal,
    logs,
    meals,
    meals_edit,
    measurements,
    medical,
    medical_ai,
    metrics,
    mfa,
    overview,
    photos,
    photos_media,
    record,
    reports,
    samples,
    sleep,
    summary,
    sync,
    tokens,
    traces,
    treatments,
    trends,
    waveforms,
    work,
    work_data,
    work_journal,
)

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(mfa.router)
api_router.include_router(account.router)
api_router.include_router(tokens.router)
api_router.include_router(overview.router)
api_router.include_router(metrics.router)
api_router.include_router(catalog.router)
api_router.include_router(measurements.router)
api_router.include_router(samples.router)
api_router.include_router(events.router)
api_router.include_router(ingest.router)
api_router.include_router(imports.router)
api_router.include_router(health_records.router)
api_router.include_router(waveforms.router)
api_router.include_router(clinical.router)
api_router.include_router(medical_ai.router)
api_router.include_router(record.router)
api_router.include_router(journal.router)
api_router.include_router(meals.router)
api_router.include_router(meals_edit.router)
api_router.include_router(work.router)
api_router.include_router(work_data.router)
api_router.include_router(work_journal.router)
api_router.include_router(logs.router)
api_router.include_router(absences.router)
api_router.include_router(evidence.router)
api_router.include_router(sleep.router)
api_router.include_router(traces.router)
api_router.include_router(medical.router)
api_router.include_router(conditions.router)
api_router.include_router(treatments.router)
api_router.include_router(appointments.router)
api_router.include_router(biology.router)
api_router.include_router(capture.router)
api_router.include_router(photos.router)
api_router.include_router(photos_media.router)
api_router.include_router(evolution.router)
api_router.include_router(dashboard.router)
api_router.include_router(data.router)
api_router.include_router(trends.router)
api_router.include_router(summary.router)
api_router.include_router(sync.router)
api_router.include_router(export.router)
api_router.include_router(reports.router)
api_router.include_router(automations.router)
api_router.include_router(automations_run.router)
