"""Initial metric catalogue (Annexe A) — a starting point, extensible.

Each entry becomes one row in ``metric_definitions``. Derived metrics
carry a ``formula`` and are never written directly; aggregates are
computed on read. Long lines are allowed here (data, not logic).
"""

from __future__ import annotations

from typing import Any

_PCT: dict[str, Any] = {"min_value": 0.0, "max_value": 100.0}
_SCORE: dict[str, Any] = {"min_value": 0.0, "max_value": 10.0}


def _m(
    key: str,
    label: str,
    domain: str,
    data_type: str,
    *,
    unit: str | None = None,
    source: str = "manual",
    agg: str = "avg",
    **extra: Any,
) -> dict[str, Any]:
    """Build a single metric-definition seed row."""
    row: dict[str, Any] = {
        "key": key,
        "label": label,
        "domain": domain,
        "data_type": data_type,
        "unit": unit,
        "source": source,
        "aggregation_hint": agg,
    }
    row.update(extra)
    return row


#: Full seed catalogue, grouped by domain (Annexe A).
CATALOG: list[dict[str, Any]] = [
    # Key & context
    _m("ctx.date", "Date", "context", "text", agg="last"),
    _m(
        "ctx.day_type",
        "Type de jour",
        "context",
        "enum",
        agg="last",
        enum_options=["arret", "travaille"],
    ),
    # Weight & photos
    _m("body.weight", "Poids du matin", "body", "float", unit="kg"),
    _m("photo.face_done", "Photo face faite", "photo", "bool", agg="last"),
    _m("photo.profil_done", "Photo profil faite", "photo", "bool", agg="last"),
    _m(
        "ai.silhouette_change",
        "Variation silhouette estimee",
        "ai",
        "text",
        source="ai",
        agg="last",
    ),
    # Sleep — times & durations
    _m(
        "sleep.bedtime",
        "Heure de coucher",
        "sleep",
        "time",
        source="watch",
        agg="last",
    ),
    _m(
        "sleep.onset",
        "Heure d'endormissement",
        "sleep",
        "time",
        source="watch",
        agg="last",
    ),
    _m(
        "sleep.wake",
        "Heure de reveil",
        "sleep",
        "time",
        source="watch",
        agg="last",
    ),
    _m(
        "sleep.time_in_bed",
        "Temps passe au lit",
        "sleep",
        "duration",
        unit="min",
        source="watch",
    ),
    _m(
        "sleep.asleep",
        "Temps reellement endormi",
        "sleep",
        "duration",
        unit="min",
        source="watch",
    ),
    _m(
        "sleep.total",
        "Duree totale de sommeil",
        "sleep",
        "duration",
        unit="min",
        source="watch",
    ),
    _m(
        "sleep.awakenings",
        "Reveils nocturnes",
        "sleep",
        "int",
        source="watch",
        agg="sum",
    ),
    _m("nap.start", "Sieste — debut", "nap", "time", agg="last"),
    _m("nap.end", "Sieste — fin", "nap", "time", agg="last"),
    _m(
        "nap.duration",
        "Sieste — duree",
        "nap",
        "duration",
        unit="min",
        source="derived",
        formula="nap.end - nap.start",
    ),
    # Sleep — stages
    _m(
        "sleep.deep",
        "Sommeil profond",
        "sleep",
        "duration",
        unit="min",
        source="watch",
    ),
    _m(
        "sleep.rem",
        "Sommeil paradoxal (REM)",
        "sleep",
        "duration",
        unit="min",
        source="watch",
    ),
    _m(
        "sleep.core",
        "Sommeil leger/core",
        "sleep",
        "duration",
        unit="min",
        source="watch",
    ),
    _m(
        "sleep.awake",
        "Eveille (nuit)",
        "sleep",
        "duration",
        unit="min",
        source="watch",
    ),
    # Sleep — nocturnal vitals
    _m(
        "sleep.spo2_avg",
        "SpO2 nocturne moyenne",
        "sleep",
        "float",
        unit="%",
        source="watch",
        **_PCT,
    ),
    _m(
        "sleep.spo2_min",
        "SpO2 nocturne minimum",
        "sleep",
        "float",
        unit="%",
        source="watch",
        agg="min",
        **_PCT,
    ),
    _m(
        "sleep.resp_rate",
        "Frequence respiratoire nocturne",
        "sleep",
        "float",
        unit="resp/min",
        source="watch",
    ),
    _m(
        "sleep.hrv",
        "VFC/HRV nocturne",
        "sleep",
        "float",
        unit="ms",
        source="watch",
    ),
    _m(
        "sleep.hr_min",
        "FC minimale de sommeil",
        "sleep",
        "int",
        unit="bpm",
        source="watch",
        agg="min",
    ),
    _m(
        "sleep.wrist_temp",
        "Ecart temperature poignet",
        "sleep",
        "float",
        unit="°C",
        source="watch",
    ),
    # CPAP machine (PPC)
    _m(
        "ppc.hours_used",
        "Heures portees",
        "ppc",
        "float",
        unit="h",
        source="ppc",
        agg="sum",
    ),
    _m("ppc.ahi", "IAH residuel", "ppc", "float", unit="evts/h", source="ppc"),
    _m(
        "ppc.leak_median",
        "Fuites — mediane",
        "ppc",
        "float",
        unit="L/min",
        source="ppc",
    ),
    _m(
        "ppc.leak_p95",
        "Fuites — P95",
        "ppc",
        "float",
        unit="L/min",
        source="ppc",
        agg="max",
    ),
    _m(
        "ppc.pressure_median",
        "Pression — mediane",
        "ppc",
        "float",
        unit="cmH2O",
        source="ppc",
    ),
    _m(
        "ppc.pressure_p90",
        "Pression — P90",
        "ppc",
        "float",
        unit="cmH2O",
        source="ppc",
        agg="max",
    ),
    _m(
        "ppc.mask_seal",
        "Etancheite masque",
        "ppc",
        "score",
        source="ppc",
        **_SCORE,
    ),
    _m(
        "ppc.central_vs_obstr",
        "Repartition apnees/hypopnees",
        "ppc",
        "text",
        source="ppc",
        agg="last",
    ),
    # Morning rest
    _m("rest.hr", "FC de repos", "rest", "int", unit="bpm", source="watch"),
    _m(
        "rest.spo2",
        "SpO2 de repos",
        "rest",
        "float",
        unit="%",
        source="watch",
        **_PCT,
    ),
    _m("symptom.breath", "Souffle", "symptom", "score", unit="/10", **_SCORE),
    _m("symptom.cough", "Toux", "symptom", "score", unit="/10", **_SCORE),
    # Workout blocks (bike / rope / shadow / strength)
    _m(
        "workout.duration",
        "Duree realisee",
        "workout",
        "duration",
        unit="min",
        agg="sum",
    ),
    _m(
        "workout.hr_avg",
        "FC moyenne",
        "workout",
        "int",
        unit="bpm",
        source="watch",
    ),
    _m(
        "workout.hr_max",
        "FC max",
        "workout",
        "int",
        unit="bpm",
        source="watch",
        agg="max",
    ),
    _m(
        "workout.spo2_during",
        "SpO2 pendant/apres",
        "workout",
        "float",
        unit="%",
        source="watch",
        agg="min",
        **_PCT,
    ),
    _m(
        "workout.borg",
        "Essoufflement (Borg)",
        "workout",
        "score",
        unit="/10",
        **_SCORE,
    ),
    _m(
        "workout.hr_recovery_1min",
        "FC 1 min apres effort",
        "workout",
        "int",
        unit="bpm",
        source="watch",
    ),
    _m(
        "workout.recovery_delta",
        "Recuperation (max - 1 min)",
        "workout",
        "int",
        unit="bpm",
        source="derived",
        formula="workout.hr_max - workout.hr_recovery_1min",
    ),
    _m("stairs.floors", "Etages montes", "workout", "int", agg="sum"),
    # Walk
    _m(
        "walk.duration",
        "Duree",
        "walk",
        "duration",
        unit="min",
        source="watch",
        agg="sum",
    ),
    _m(
        "walk.distance",
        "Distance",
        "walk",
        "float",
        unit="km",
        source="watch",
        agg="sum",
    ),
    _m("walk.hr_avg", "FC moyenne", "walk", "int", unit="bpm", source="watch"),
    _m(
        "walk.spo2",
        "SpO2",
        "walk",
        "float",
        unit="%",
        source="watch",
        agg="min",
        **_PCT,
    ),
    _m("walk.borg", "Essoufflement", "walk", "score", unit="/10", **_SCORE),
    # Treatment / adherence
    _m("med.candesartan", "Candesartan pris", "med", "bool", agg="last"),
    _m("med.paroxetine", "Paroxetine prise", "med", "bool", agg="last"),
    _m("med.neb1", "Nebulisation 1", "med", "bool", agg="last"),
    _m("med.neb2", "Nebulisation 2", "med", "bool", agg="last"),
    _m("med.neb3", "Nebulisation 3", "med", "bool", agg="last"),
    _m("med.rinse", "Rincage bouche post-nebu", "med", "bool", agg="last"),
    _m("med.zolpidem", "Zolpidem pris", "med", "bool", agg="last"),
    _m("med.zolpidem_time", "Heure zolpidem", "med", "time", agg="last"),
    # Habits (tobacco / coffee / water)
    _m("habit.cigarettes", "Cigarettes", "habit", "int", agg="sum"),
    _m("habit.urges_broken", "Envies cassees", "habit", "int", agg="sum"),
    _m("habit.coffee", "Cafes", "habit", "int", agg="sum"),
    _m("water.bottles_1_5", "Bouteilles d'eau 1,5 L", "water", "float"),
    _m(
        "hydration.liters",
        "Hydratation totale",
        "hydration",
        "float",
        unit="L",
        source="derived",
        formula="water.bottles_1_5 * 1.5",
    ),
    # Food
    _m("food.breakfast", "Petit-dejeuner", "food", "text", agg="last"),
    _m("food.snack_am", "Collation 10 h", "food", "text", agg="last"),
    _m("food.lunch", "Dejeuner", "food", "text", agg="last"),
    _m("food.snack_pm", "Collation 16 h", "food", "text", agg="last"),
    _m("food.dinner", "Diner", "food", "text", agg="last"),
    _m("food.grignotage", "Grignotage / extra", "food", "text", agg="last"),
    _m("food.plan_respected", "Repas respectes", "food", "bool", agg="last"),
    _m("food.deviations", "Ecarts", "food", "text", agg="last"),
    # General state
    _m("state.fatigue", "Fatigue", "state", "score", unit="/10", **_SCORE),
    _m(
        "state.mood_energy",
        "Moral / energie",
        "state",
        "score",
        unit="/10",
        **_SCORE,
    ),
    _m(
        "state.post_effort_crash",
        "Malaise post-effort",
        "state",
        "bool",
        agg="last",
    ),
    _m("state.notes", "Notes libres", "state", "text", agg="last"),
]
